server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
---
spring:
  profiles: cloud
  main:
    banner-mode: "off"
server:
  port: 8080
management:
  port: 8081
eureka:
  instance:
    non-secure-port: ${server.port}