server:
  port: 8888
management:
  port: 8081
spring:
  profiles:
    active: native
  main:
    banner-mode: "off"
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/repository
